In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text

In [2]:
engine = create_engine(
    "mysql+pymysql://root:%40pass123@localhost:3306/bookhub"
)

print("Connected!")

Connected!

In [3]:
books = pd.read_csv(
    "../raw/Books.csv",
    encoding="latin-1",
    low_memory=False
)

books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
books = books.rename(columns={
    "ISBN":"isbn",
    "Book-Title":"title",
    "Book-Author":"author",
    "Year-Of-Publication":"publication_year",
    "Publisher":"publisher",
    "Image-URL-L":"image_url"
})

In [5]:
books = books[
[
"isbn",
"title",
"author",
"publication_year",
"publisher",
"image_url"
]
]

In [12]:
books = books.drop_duplicates(subset=["isbn"])

books["publication_year"] = pd.to_numeric(
    books["publication_year"],
    errors="coerce"
)

# Keep only valid publication years
books = books[(books["publication_year"] >= 1900) & (books["publication_year"] <= 2024)]

# Fill only text columns
books["author"] = books["author"].fillna("Unknown")
books["publisher"] = books["publisher"].fillna("Unknown")
books["image_url"] = books["image_url"].fillna("")

In [7]:
books["isbn"].duplicated().sum()

np.int64(0)

In [8]:
with engine.begin() as conn:
    conn.execute(text("DELETE FROM books"))

In [9]:
pd.read_sql("SELECT COUNT(*) total FROM books", engine)

   total
0      0

In [13]:
print(books.shape)
print(books["isbn"].duplicated().sum())
print(books.isnull().sum())

(266723, 6)
0
isbn                0
title               0
author              0
publication_year    0
publisher           0
image_url           0
dtype: int64

In [14]:
from sqlalchemy import text

for i in range(0, len(books), 1000):
    batch = books.iloc[i:i+1000]

    try:
        batch.to_sql(
            "books",
            con=engine,
            if_exists="append",
            index=False
        )
        print(f"Inserted {i + len(batch)} rows")

    except Exception as e:
        print(f"Error at batch starting from row {i}")
        print(e)

        print("\nProblematic rows:")
        print(batch.head(10))

        break

Error at batch starting from row 0
Execution failed on sql 'INSERT INTO books (isbn, title, author, publication_year, publisher, image_url) VALUES (:isbn, :title, :author, :publication_year, :publisher, :image_url)': (pymysql.err.IntegrityError) (1062, "Duplicate entry '0195153448' for key 'books.isbn'")
[SQL: INSERT INTO books (isbn, title, author, publication_year, publisher, image_url) VALUES (%(isbn)s, %(title)s, %(author)s, %(publication_year)s, %(publisher)s, %(image_url)s)]
[parameters: [{'isbn': '0195153448', 'title': 'Classical Mythology', 'author': 'Mark P. O. Morford', 'publication_year': 2002.0, 'publisher': 'Oxford University Press', 'image_url': 'http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg'}, {'isbn': '0002005018', 'title': 'Clara Callan', 'author': 'Richard Bruce Wright', 'publication_year': 2001.0, 'publisher': 'HarperFlamingo Canada', 'image_url': 'http://images.amazon.com/images/P/0002005018.01.LZZZZZZZ.jpg'}, {'isbn': '0060973129', 'title': 'Decision in Normandy', 'author': "Carlo D'Este", 'publication_year': 1991.0, 'publisher': 'HarperPerennial', 'image_url': 'http://images.amazon.com/images/P/0060973129.01.LZZZZZZZ.jpg'}, {'isbn': '0374157065', 'title': 'Flu: The Story of the Great Influenza Pandemic of 1918 and the Search for the Virus That Caused It', 'author': 'Gina Bari Kolata', 'publication_year': 1999.0, 'publisher': 'Farrar Straus Giroux', 'image_url': 'http://images.amazon.com/images/P/0374157065.01.LZZZZZZZ.jpg'}, {'isbn': '0393045218', 'title': 'The Mummies of Urumchi', 'author': 'E. J. W. Barber', 'publication_year': 1999.0, 'publisher': 'W. W. Norton &amp; Company', 'image_url': 'http://images.amazon.com/images/P/0393045218.01.LZZZZZZZ.jpg'}, {'isbn': '0399135782', 'title': "The Kitchen God's Wife", 'author': 'Amy Tan', 'publication_year': 1991.0, 'publisher': 'Putnam Pub Group', 'image_url': 'http://images.amazon.com/images/P/0399135782.01.LZZZZZZZ.jpg'}, {'isbn': '0425176428', 'title': "What If?: The World's Foremost Military Historians Imagine What Might Have Been", 'author': 'Robert Cowley', 'publication_year': 2000.0, 'publisher': 'Berkley Publishing Group', 'image_url': 'http://images.amazon.com/images/P/0425176428.01.LZZZZZZZ.jpg'}, {'isbn': '0671870432', 'title': 'PLEADING GUILTY', 'author': 'Scott Turow', 'publication_year': 1993.0, 'publisher': 'Audioworks', 'image_url': 'http://images.amazon.com/images/P/0671870432.01.LZZZZZZZ.jpg'}  ... displaying 10 of 1000 total bound parameter sets ...  {'isbn': '044022165X', 'title': 'The Rainmaker', 'author': 'JOHN GRISHAM', 'publication_year': 1996.0, 'publisher': 'Dell', 'image_url': 'http://images.amazon.com/images/P/044022165X.01.LZZZZZZZ.jpg'}, {'isbn': '0373123485', 'title': "On The Tycoon's Terms   Do Not Disturb! (Harlequin Presents, 2348)", 'author': 'Sandra Field', 'publication_year': 2003.0, 'publisher': 'Harlequin', 'image_url': 'http://images.amazon.com/images/P/0373123485.01.LZZZZZZZ.jpg'}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

Problematic rows:
         isbn                                              title  \
0  0195153448                                Classical Mythology
1  0002005018                                       Clara Callan
2  0060973129                               Decision in Normandy
3  0374157065  Flu: The Story of the Great Influenza Pandemic...
4  0393045218                             The Mummies of Urumchi
5  0399135782                             The Kitchen God's Wife
6  0425176428  What If?: The World's Foremost Military Histor...
7  0671870432                                    PLEADING GUILTY
8  0679425608  Under the Black Flag: The Romance and the Real...
9  074322678X            Where You'll Find Me: And Other Stories

                 author  publication_year                   publisher  \
0    Mark P. O. Morford            2002.0     Oxford University Press
1  Richard Bruce Wright            2001.0       HarperFlamingo Canada
2          Carlo D'Este            1991.0             HarperPerennial
3      Gina Bari Kolata            1999.0        Farrar Straus Giroux
4       E. J. W. Barber            1999.0  W. W. Norton &amp; Company
5               Amy Tan            1991.0            Putnam Pub Group
6         Robert Cowley            2000.0    Berkley Publishing Group
7           Scott Turow            1993.0                  Audioworks
8       David Cordingly            1996.0                Random House
9           Ann Beattie            2002.0                    Scribner

                                           image_url
0  http://images.amazon.com/images/P/0195153448.0...
1  http://images.amazon.com/images/P/0002005018.0...
2  http://images.amazon.com/images/P/0060973129.0...
3  http://images.amazon.com/images/P/0374157065.0...
4  http://images.amazon.com/images/P/0393045218.0...
5  http://images.amazon.com/images/P/0399135782.0...
6  http://images.amazon.com/images/P/0425176428.0...
7  http://images.amazon.com/images/P/0671870432.0...
8  http://images.amazon.com/images/P/0679425608.0...
9  http://images.amazon.com/images/P/074322678X.0...

In [11]:
pd.read_sql(
    "SELECT COUNT(*) total FROM books",
    engine
)

   total
0   6000

In [15]:
import pandas as pd

pd.read_sql("""
SELECT COUNT(*) AS total
FROM books;
""", engine)

   total
0   6000

In [16]:
pd.read_sql("""
SELECT isbn
FROM books
WHERE isbn='0195153448';
""", engine)

         isbn
0  0195153448

In [17]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE books;"))

print("Books table truncated.")

Books table truncated.

In [18]:
import pandas as pd

pd.read_sql(
    "SELECT COUNT(*) AS total FROM books;",
    engine
)

   total
0      0

In [19]:
pd.read_sql("SELECT DATABASE();", engine)

  DATABASE()
0    bookhub